# Generated by Django 4.1.2 on 2022-10-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
