# Generated by Django 4.1.2 on 2022-10-05 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedIPs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_post', to='api.post')),
            ],
        ),
    ]
