# Generated by Django 4.1.2 on 2022-10-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_visitedips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
