# Generated by Django 4.1.2 on 2022-10-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedips',
            name='ip',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
